# Generated by Django 5.0.2 on 2024-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='company_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Default none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_size',
            field=models.CharField(choices=[('size_1_9', '1-9'), ('size_10_49', '10-49'), ('size_50_99', '50-99'), ('size_100', '100+')], default='size_1_9', max_length=20),
        ),
    ]
