# Generated by Django 5.0.2 on 2024-03-21 08:41

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
