# Generated by Django 5.0.2 on 2024-03-21 10:48

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_country',
            field=django_countries.fields.CountryField(default='Nigeria', max_length=2),
        ),
    ]
