# Generated by Django 5.0.2 on 2024-11-20 07:20

from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify

def generate_job_slugs(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.all():
        counter = 1
        slug = slugify(f"{job.title}-{job.company_name}")
        while Job.objects.filter(slug=slug).exists():
            slug = slugify(f"{job.title}-{job.company_name}-{counter}")
            counter += 1
        job.slug = slug
        job.save()

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_company_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.RunPython(generate_job_slugs),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='onsite', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='jobs_job_status_0e6ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company_country', 'status'], name='jobs_job_company_1d4d2e_idx'),
        ),
    ]
